#include <Geode/Geode.hpp>
#include <Geode/modify/EditorUI.hpp>

#include <alphalaneous.editortab_api/include/EditorTabs.hpp>

#include "CustomObjectsAPI.hpp"

using namespace geode::prelude;

class $modify(EditorUI) {
    bool init(LevelEditorLayer* editorLayer) {
        if (!EditorUI::init(editorLayer)) return false;

        EditorTabs::addTab(this, TabType::BUILD, "custom-objects"_spr, [this](EditorUI* ui, CCMenuItemToggler* toggler) -> CCNode* {
            CCLabelBMFont* textLabel = CCLabelBMFont::create("+", "bigFont.fnt");
            textLabel->setScale(0.5f);
            EditorTabUtils::setTabIcon(toggler, textLabel);

            auto buttons = CCArray::create();
            auto manager = CustomObjectsManager::get();
            manager->forEachCustomObject([this, buttons](auto obj) {
                buttons->addObject(getCreateBtn(obj.id, 4));
            });
 
            return EditorTabUtils::createEditButtonBar(buttons, ui);
        });

        return true;
    } // init

    #define $compare1(var) if (obj1->var != obj2->var) log::info(#var" = {}, {}", obj1->var, obj2->var)
    #define $compare2(var) if (obj1->var != obj2->var) log::info(#var)

    gd::string copyObjects(CCArray* objects, bool copyColors, bool sort) {
        bool actuallyDoSomething = false;
        auto obj1 = static_cast<EffectGameObject*>(objects->objectAtIndex(0));
        auto obj2 = static_cast<EffectGameObject*>(objects->objectAtIndex(1));

        if (obj1 && actuallyDoSomething) log::info("{}", obj1->getSaveString(GJBaseGameLayer::get()));
        if (!obj1 || !obj2 || !actuallyDoSomething) return EditorUI::copyObjects(objects, copyColors, sort);

        $compare1(m_someOtherIndex);
        $compare1(m_innerSectionIndex);
        $compare1(m_outerSectionIndex);
        $compare1(m_middleSectionIndex);
        $compare1(m_hasExtendedCollision);
        $compare2(m_maybeGroupColor);
        $compare1(m_unk280);
        $compare1(m_unk281);
        $compare1(m_blackChildRelated);
        $compare1(m_unk288);
        $compare1(m_editorEnabled);
        $compare1(m_isGroupDisabled);
        $compare1(m_unk28B);
        $compare1(m_unk28c);
        $compare1(m_activeMainColorID);
        $compare1(m_activeDetailColorID);
        $compare1(m_baseUsesHSV);
        $compare1(m_detailUsesHSV);
        $compare1(m_positionXOffset);
        $compare1(m_positionYOffset);
        $compare1(m_rotationXOffset);
        $compare1(m_unk2A8);
        $compare1(m_rotationYOffset);
        $compare1(m_unk2B0);
        $compare1(m_scaleXOffset);
        $compare1(m_scaleYOffset);
        $compare1(m_unk2BC);
        $compare1(m_unk2C0);
        $compare1(m_tempOffsetXRelated);
        $compare1(m_isFlipX);
        $compare1(m_isFlipY);
        $compare2(m_customBoxOffset);
        $compare1(m_boxOffsetCalculated);
        $compare2(m_boxOffset);
        $compare2(m_orientedBox);
        $compare1(m_shouldUseOuterOb);
        $compare2(m_glowSprite);
        $compare1(m_unk2F8);
        $compare1(m_width);
        $compare1(m_height);
        $compare1(m_hasSpecialChild);
        $compare1(m_isActivated);
        $compare1(m_isDisabled2);
        $compare2(m_particle);
        $compare2(m_particleString);
        $compare1(m_hasParticles);
        $compare1(m_particleUseObjectColor);
        $compare1(m_hasColorSprite);
        $compare2(m_unk31c);
        $compare1(m_isSomeSpriteScalable);
        $compare1(m_textureRect);
        $compare1(m_isDirty);
        $compare1(m_isObjectPosDirty);
        $compare1(m_isUnmodifiedPosDirty);
        $compare1(m_unk33C);
        $compare1(m_objectRect);
        $compare1(m_isObjectRectDirty);
        $compare1(m_isOrientedBoxDirty);
        $compare1(m_colorSpriteLocked);
        $compare1(m_unk353);
        $compare1(m_canRotateFree);
        $compare1(m_isMirroredByScale);
        $compare1(m_linkedGroup);
        $compare1(m_unk35C);
        $compare1(m_colorType);
        $compare1(m_childColorType);
        $compare1(m_shouldBlendBase);
        $compare1(m_shouldBlendDetail);
        $compare1(m_hasCustomChild);
        $compare1(m_unk367);
        $compare2(m_colorSprite);
        $compare1(m_unk370);
        $compare1(m_objectRadius);
        $compare1(m_isRotationAligned);
        $compare1(m_spriteWidthScale);
        $compare1(m_spriteHeightScale);
        $compare1(m_uniqueID);
        $compare2(m_objectType);
        $compare2(m_savedObjectType);
        $compare1(m_unk390);
        $compare1(m_unmodifiedPositionX);
        $compare1(m_unmodifiedPositionY);
        $compare1(m_positionX);
        $compare1(m_positionY);
        $compare1(m_startPosition);
        $compare1(m_usesAudioScale);
        $compare1(m_hasNoAudioScale);
        $compare1(m_isDisabled);
        $compare1(m_startRotationX);
        $compare1(m_startRotationY);
        $compare1(m_startScaleX);
        $compare1(m_startScaleY);
        $compare1(m_customScaleX);
        $compare1(m_customScaleY);
        $compare1(m_startFlipX);
        $compare1(m_startFlipY);
        $compare1(m_unk3ee);
        $compare1(m_isInvisible);
        $compare1(m_unk3D8);
        $compare1(m_unk3DC);
        $compare1(m_unk3DE);
        $compare1(m_unk3E0);
        $compare1(m_unk3E2);
        $compare1(m_enterChannel);
        $compare1(m_objectMaterial);
        $compare1(m_unk3E8);
        $compare1(m_parentMode);
        $compare1(m_hasNoGlow);
        $compare1(m_targetColor);
        $compare1(m_objectID);
        $compare1(m_unk3F8);
        $compare1(m_isSolid);
        $compare1(m_ignoreEnter);
        $compare1(m_ignoreFade);
        $compare1(m_unk3FC);
        $compare1(m_unk3FD);
        $compare1(m_customSpriteColor);
        $compare1(m_customColorType);
        $compare1(m_isDontEnter);
        $compare1(m_isDontFade);
        $compare1(m_hasNoEffects);
        $compare1(m_hasNoParticles);
        $compare1(m_defaultZOrder);
        $compare1(m_unk40C);
        $compare1(m_colorZLayerRelated);
        $compare1(m_unk40E);
        $compare1(m_unk410);
        $compare1(m_unk414);
        $compare1(m_particleLocked);
        $compare1(m_property53);
        $compare1(m_gmUnkBool4Related);
        $compare1(m_unk421);
        $compare1(m_unk422);
        $compare1(m_cantColorGlow);
        $compare1(m_opacityMod);
        $compare1(m_slopeUphill);
        $compare1(m_slopeDirection);
        $compare1(m_maybeShouldFixSlopes);
        $compare1(m_opacityMod2);
        $compare2(m_baseColor);
        $compare2(m_detailColor);
        $compare1(m_unk448);
        $compare2(m_defaultZLayer);
        $compare1(m_zFixedZLayer);
        $compare2(m_zLayer);
        $compare1(m_zOrder);
        $compare1(m_unk45c);
        $compare1(m_isSelected);
        $compare1(m_unk460);
        $compare2(m_unk464);
        $compare1(m_shouldUpdateColorSprite);
        $compare1(m_unk46d);
        $compare1(m_hasGroupParent);
        $compare1(m_hasAreaParent);
        $compare1(m_scaleX);
        $compare1(m_scaleY);
        $compare2(m_groups);
        $compare1(m_groupCount);
        $compare1(m_hasGroupParentsString);
        $compare2(m_colorGroups);
        $compare1(m_colorGroupCount);
        $compare2(m_opacityGroups);
        $compare1(m_opacityGroupCount);
        $compare1(m_editorLayer);
        $compare1(m_editorLayer2);
        $compare1(m_enabledGroupsCounter);
        $compare1(m_updateCustomContentSize);
        $compare1(m_hasContentSize);
        $compare1(m_isNoTouch);
        $compare2(m_lastSize);
        $compare2(m_lastPosition);
        $compare1(m_unk4C0);
        $compare1(m_unk4C4);
        $compare1(m_unk4C8);
        $compare1(m_unk4CC);
        $compare2(m_classType);
        $compare1(m_isTrigger);
        $compare1(m_isSpawnOrderTrigger);
        $compare1(m_isColorTrigger);
        $compare1(m_dontIgnoreDuration);
        $compare1(m_canBeControlled);
        $compare1(m_isSpawnOrderTrigger2);
        $compare1(m_isStartPos);
        $compare1(m_isHighDetail);
        $compare2(m_unk4E0);
        $compare2(m_unk4E8);
        $compare2(m_goEffectManager);
        $compare1(m_unk4F8);
        $compare1(m_isDecoration);
        $compare1(m_isDecoration2);
        $compare1(m_unk4fb);
        $compare1(m_maybeNotColorable);
        $compare1(m_isPassable);
        $compare1(m_isHide);
        $compare1(m_isNonStickX);
        $compare1(m_isNonStickY);
        $compare1(m_isIceBlock);
        $compare1(m_isGripSlope);
        $compare1(m_isScaleStick);
        $compare1(m_isExtraSticky);
        $compare1(m_isDontBoostY);
        $compare1(m_isDontBoostX);
        $compare1(m_unk507);
        $compare1(m_unk508);
        $compare1(m_unk50C);
        $compare1(m_pixelScaleX);
        $compare1(m_pixelScaleY);
        $compare1(m_mainColorKeyIndex);
        $compare1(m_detailColorKeyIndex);
        $compare1(m_areaOpacityRelated);
        $compare1(m_areaOpacityRelated2);
        $compare1(m_areaOpacityRelated3);
        $compare1(m_unk52C);
        $compare1(m_unk530);
        $compare1(m_isUIObject);
        $compare1(m_unk532);

        $compare1(m_poweredOn);
        $compare1(m_state);
        $compare1(m_animationRandomizedStartValue);
        $compare1(m_animationStart);
        $compare1(m_unk540);
        $compare1(m_unk544);
        $compare1(m_unk548);
        $compare1(m_randomFrameTime);
        $compare1(m_visible);
        $compare1(m_shouldNotHideAnimFreeze);
        $compare1(m_usesSpecialAnimation);
        $compare1(m_frameTime);
        $compare1(m_frames);
        $compare1(m_hasCustomAnimation);
        $compare1(m_hasCustomRotation);
        $compare1(m_disableRotation);
        $compare1(m_rotationSpeed);
        $compare1(m_rotationAngle);
        $compare1(m_rotationDelta);
        $compare1(m_rotationAnimationSpeed);
        $compare1(m_animationRandomizedStart);
        $compare1(m_animationSpeed);
        $compare1(m_animationShouldUseSpeed);
        $compare1(m_animateOnTrigger);
        $compare1(m_disableDelayedLoop);
        $compare1(m_disableAnimShine);
        $compare1(m_singleFrame);
        $compare1(m_animationOffset);
        $compare1(m_animationTriggered);
        $compare1(m_unkAnimationInt);
        $compare1(m_maybeAnimationVariableXInt);
        $compare1(m_maybeAnimationVariableYInt);
        $compare1(m_animateOnlyWhenActive);
        $compare1(m_isNoMultiActivate);
        $compare1(m_isMultiActivate);
        $compare1(m_activated);
        $compare1(m_activatedByPlayer1);
        $compare1(m_activatedByPlayer2);
        $compare1(m_hasUniqueCoin);

        $compare1(m_unknownBool);
        $compare2(m_triggerTargetColor);
        $compare1(m_duration);
        $compare1(m_opacity);
        $compare1(m_triggerEffectPlaying);
        $compare1(m_targetGroupID);
        $compare1(m_centerGroupID);
        $compare1(m_isTouchTriggered);
        $compare1(m_isSpawnTriggered);
        $compare1(m_hasCenterEffect);
        $compare1(m_shakeStrength);
        $compare1(m_shakeInterval);
        $compare1(m_tintGround);
        $compare1(m_usesPlayerColor1);
        $compare1(m_usesPlayerColor2);
        $compare1(m_usesBlending);
        $compare2(m_moveOffset);
        $compare2(m_easingType);
        $compare1(m_easingRate);
        $compare1(m_lockToPlayerX);
        $compare1(m_lockToPlayerY);
        $compare1(m_lockToCameraX);
        $compare1(m_lockToCameraY);
        $compare1(m_useMoveTarget);
        $compare2(m_moveTargetMode);
        $compare1(m_moveModX);
        $compare1(m_moveModY);
        $compare1(m_smallStep);
        $compare1(m_isDirectionFollowSnap360);
        $compare1(m_targetModCenterID);
        $compare1(m_directionModeDistance);
        $compare1(m_isDynamicMode);
        $compare1(m_isSilent);
        $compare1(m_specialTarget);
        $compare1(m_rotationDegrees);
        $compare1(m_times360);
        $compare1(m_lockObjectRotation);
        $compare1(m_rotationTargetID);
        $compare1(m_rotationOffset);
        $compare1(m_dynamicModeEasing);
        $compare1(m_followXMod);
        $compare1(m_followYMod);
        $compare1(m_followYSpeed);
        $compare1(m_followYDelay);
        $compare1(m_followYOffset);
        $compare1(m_followYMaxSpeed);
        $compare1(m_fadeInDuration);
        $compare1(m_holdDuration);
        $compare1(m_fadeOutDuration);
        $compare1(m_pulseMode);
        $compare1(m_pulseTargetType);
        $compare2(m_hsvValue);
        $compare1(m_copyColorID);
        $compare1(m_copyOpacity);
        $compare1(m_pulseMainOnly);
        $compare1(m_pulseDetailOnly);
        $compare1(m_pulseExclusive);
        $compare1(m_legacyHSV);
        $compare1(m_activateGroup);
        $compare1(m_touchHoldMode);
        $compare2(m_touchToggleMode);
        $compare2(m_touchPlayerMode);
        $compare1(m_isDualMode);
        $compare1(m_animationID);
        $compare1(m_spawnXPosition);
        $compare1(m_spawnOrder);
        $compare1(m_isMultiTriggered);
        $compare1(m_previewDisable);
        $compare1(m_spawnOrdered);
        $compare1(m_triggerOnExit);
        $compare1(m_itemID2);
        $compare1(m_controlID);
        $compare1(m_targetControlID);
        $compare1(m_isDynamicBlock);
        $compare1(m_itemID);
        $compare1(m_targetPlayer1);
        $compare1(m_targetPlayer2);
        $compare1(m_followCPP);
        $compare1(m_subtractCount);
        $compare1(m_collectibleIsPickupItem);
        $compare1(m_collectibleIsToggleTrigger);
        $compare1(m_collectibleParticleID);
        $compare1(m_collectiblePoints);
        $compare1(m_hasNoAnimation);
        $compare2(m_unk698);
        $compare1(m_forceModID);
        $compare1(m_rotateFollowP1);
        $compare1(m_rotateFollowP2);
        $compare1(m_unk6a8);
        $compare1(m_unk6ac);
        $compare1(m_unk6b0);
        $compare1(m_unk6b4);
        $compare1(m_gravityValue);
        $compare1(m_isSinglePTouch);
        $compare1(m_zoomValue);
        $compare1(m_cameraIsFreeMode);
        $compare1(m_cameraEditCameraSettings);
        $compare1(m_cameraEasingValue);
        $compare1(m_cameraPaddingValue);
        $compare1(m_cameraDisableGridSnap);
        $compare1(m_endReversed);
        $compare1(m_timeWarpTimeMod);
        $compare1(m_shouldPreview);
        $compare1(m_ordValue);
        $compare1(m_channelValue);
        $compare1(m_isReverse);
        $compare1(m_speedModType);
        $compare2(m_speedStart);
        $compare1(m_secretCoinID);
        $compare1(m_unk6f4);
        $compare1(m_unk6f5);
        $compare1(m_endPosition);
        $compare1(m_spawnTriggerDelay);
        $compare1(m_gravityMod);
        $compare1(m_unk708);
        $compare2(m_objectLabel);
        $compare1(m_ignoreGroupParent);
        $compare1(m_ignoreLinkedObjects);
        $compare1(m_channelChanged);
        
        return EditorUI::copyObjects(objects, copyColors, sort);
    }
};