#include <Geode/Geode.hpp>
#include <Geode/modify/EditorUI.hpp>

#include <alphalaneous.editortab_api/include/EditorTabs.hpp>

#include "CustomObjectsAPI.hpp"

using namespace geode::prelude;

class $modify(EditorUI) {
    bool init(LevelEditorLayer* editorLayer) {
        if (!EditorUI::init(editorLayer)) return false;

        EditorTabs::addTab(this, TabType::BUILD, "custom-objects"_spr, [this](EditorUI* ui, CCMenuItemToggler* toggler) -> CCNode* {
            CCLabelBMFont* textLabel = CCLabelBMFont::create("+", "bigFont.fnt");
            textLabel->setScale(0.5f);
            EditorTabUtils::setTabIcon(toggler, textLabel);

            auto buttons = CCArray::create();
            auto manager = CustomObjectsManager::get();
            manager->forEachCustomObject([this, buttons](auto obj) {
                buttons->addObject(getCreateBtn(obj.id, 4));
            });
 
            return EditorTabUtils::createEditButtonBar(buttons, ui);
        });

        return true;
    } // init

    // #define $compare(val) if (obj1->val != obj2->val) log::info(#val" = {} | {}", obj1->val, obj2->val)
    // #define $compare2(val) if (obj1->val != obj2->val) log::info(#val" = {} | {}", (int)obj1->val, (int)obj2->val)

    #define $compare(val) obj1->val = obj2->val
    #define $compare2(val) obj1->val = obj2->val

    gd::string copyObjects(CCArray* objects, bool copyColors, bool sort) {
        auto obj1 = static_cast<EffectGameObject*>(objects->objectAtIndex(0));
        auto obj2 = static_cast<EffectGameObject*>(objects->objectAtIndex(1));
        log::info("obj1 = {}", obj1);
        log::info("obj2 = {}", obj2);

        $compare(m_someOtherIndex);
        $compare(m_innerSectionIndex);
        $compare(m_outerSectionIndex);
        $compare(m_middleSectionIndex);
        $compare(m_hasExtendedCollision);
        $compare(m_unk280);
        $compare(m_unk281);
        $compare(m_blackChildRelated);
        $compare(m_unk288);
        $compare(m_editorEnabled);
        $compare(m_isGroupDisabled);
        $compare(m_unk28B);
        $compare(m_unk28c);
        $compare(m_activeMainColorID);
        $compare(m_activeDetailColorID);
        $compare(m_baseUsesHSV);
        $compare(m_detailUsesHSV);
        $compare(m_positionXOffset);
        $compare(m_positionYOffset);
        $compare(m_rotationXOffset);
        $compare(m_unk2A8);
        $compare(m_rotationYOffset);
        $compare(m_unk2B0);
        $compare(m_scaleXOffset);
        $compare(m_scaleYOffset);
        $compare(m_unk2BC);
        $compare(m_unk2C0);
        $compare(m_tempOffsetXRelated);
        $compare(m_isFlipX);
        $compare(m_isFlipY);
        // $compare(m_customBoxOffset);
        $compare(m_boxOffsetCalculated);
        // $compare(m_boxOffset);
        // $compare(m_orientedBox);
        $compare(m_shouldUseOuterOb);
        // $compare(m_glowSprite);
        $compare(m_unk2F8);
        $compare(m_width);
        $compare(m_height);
        $compare(m_hasSpecialChild);
        $compare(m_isActivated);
        $compare(m_isDisabled2);
        // $compare(m_particle);
        // $compare(m_particleString);
        $compare(m_hasParticles);
        $compare(m_particleUseObjectColor);
        $compare(m_hasColorSprite);
        $compare(m_unk31c);
        $compare(m_isSomeSpriteScalable);
        // $compare(m_textureRect);
        $compare(m_isDirty);
        $compare(m_isObjectPosDirty);
        $compare(m_isUnmodifiedPosDirty);
        $compare(m_unk33C);
        // $compare(m_objectRect);
        $compare(m_isObjectRectDirty);
        $compare(m_isOrientedBoxDirty);
        $compare(m_colorSpriteLocked);
        $compare(m_unk353);
        $compare(m_canRotateFree);
        $compare(m_isMirroredByScale);
        $compare(m_linkedGroup);
        $compare(m_unk35C);
        $compare(m_colorType);
        $compare(m_childColorType);
        $compare(m_shouldBlendBase);
        $compare(m_shouldBlendDetail);
        $compare(m_hasCustomChild);
        $compare(m_unk367);
        // $compare(m_colorSprite);
        $compare(m_unk370);
        $compare(m_objectRadius);
        $compare(m_isRotationAligned);
        $compare(m_spriteWidthScale);
        $compare(m_spriteHeightScale);
        $compare(m_uniqueID);
        $compare2(m_objectType);
        $compare2(m_savedObjectType);
        $compare(m_unk390);
        $compare(m_unmodifiedPositionX);
        $compare(m_unmodifiedPositionY);
        $compare(m_positionX);
        $compare(m_positionY);
        $compare(m_startPosition);
        $compare(m_unk3b8);
        $compare(m_hasNoAudioScale);
        $compare(m_isDisabled);
        $compare(m_startRotationX);
        $compare(m_startRotationY);
        $compare(m_startScaleX);
        $compare(m_startScaleY);
        $compare(m_customScaleX);
        $compare(m_customScaleY);
        $compare(m_startFlipX);
        $compare(m_startFlipY);
        $compare(m_unk3ee);
        $compare(m_isInvisible);
        $compare(m_unk3D8);
        $compare(m_unk3DC);
        $compare(m_unk3DE);
        $compare(m_unk3E0);
        $compare(m_unk3E2);
        $compare(m_enterChannel);
        $compare(m_objectMaterial);
        $compare(m_unk3E8);
        // $compare(m_parentMode);
        $compare(m_hasNoGlow);
        $compare(m_targetColor);
        // $compare(m_objectID);
        $compare(m_unk3F8);
        $compare(m_isSolid);
        $compare(m_ignoreEnter);
        $compare(m_ignoreFade);
        $compare(m_unk3FC);
        $compare(m_unk3FD);
        $compare(m_customSpriteColor);
        $compare(m_customColorType);
        $compare(m_isDontEnter);
        $compare(m_isDontFade);
        $compare(m_hasNoEffects);
        $compare(m_hasNoParticles);
        $compare(m_defaultZOrder);
        $compare(m_unk40C);
        $compare(m_colorZLayerRelated);
        $compare(m_unk40E);
        $compare(m_unk410);
        $compare(m_unk414);
        $compare(m_particleLocked);
        $compare(m_property53);
        $compare(m_gmUnkBool4Related);
        $compare(m_unk421);
        $compare(m_unk422);
        $compare(m_cantColorGlow);
        $compare(m_opacityMod);
        $compare(m_slopeUphill);
        $compare(m_slopeDirection);
        $compare(m_maybeShouldFixSlopes);
        $compare(m_opacityMod2);
        $compare(m_unk448);
        $compare2(m_defaultZLayer);
        $compare(m_zFixedZLayer);
        $compare2(m_zLayer);
        $compare(m_zOrder);
        $compare(m_unk45c);
        $compare(m_isSelected);
        $compare(m_unk460);
        $compare(m_unk464);
        $compare(m_shouldUpdateColorSprite);
        $compare(m_unk46d);
        $compare(m_hasGroupParent);
        $compare(m_hasAreaParent);
        $compare(m_scaleX);
        $compare(m_scaleY);
        $compare(m_groupCount);
        $compare(m_hasGroupParentsString);
        $compare(m_colorGroupCount);
        $compare(m_opacityGroupCount);
        $compare(m_editorLayer);
        $compare(m_editorLayer2);
        $compare(m_enabledGroupsCounter);
        $compare(m_updateCustomContentSize);
        $compare(m_hasContentSize);
        $compare(m_isNoTouch);
        $compare(m_lastSize);
        $compare(m_lastPosition);
        $compare(m_unk4C0);
        $compare(m_unk4C4);
        $compare(m_unk4C8);
        $compare(m_unk4CC);
        // $compare2(m_classType);
        $compare(m_isTrigger);
        $compare(m_isSpawnOrderTrigger);
        $compare(m_isColorTrigger);
        $compare(m_dontIgnoreDuration);
        $compare(m_canBeControlled);
        $compare(m_isSpawnOrderTrigger2);
        $compare(m_isStartPos);
        $compare(m_isHighDetail);
        // $compare(m_unk4E0);
        // $compare(m_unk4E8);
        // $compare(m_goEffectManager);
        $compare(m_unk4F8);
        $compare(m_isDecoration);
        $compare(m_isDecoration2);
        $compare(m_unk4fb);
        $compare(m_maybeNotColorable);
        $compare(m_isPassable);
        $compare(m_isHide);
        $compare(m_isNonStickX);
        $compare(m_isNonStickY);
        $compare(m_isIceBlock);
        $compare(m_isGripSlope);
        $compare(m_isScaleStick);
        $compare(m_isExtraSticky);
        $compare(m_isDontBoostY);
        $compare(m_isDontBoostX);
        $compare(m_unk507);
        $compare(m_unk508);
        $compare(m_unk50C);
        $compare(m_pixelScaleX);
        $compare(m_pixelScaleY);
        $compare(m_mainColorKeyIndex);
        $compare(m_detailColorKeyIndex);
        $compare(m_areaOpacityRelated);
        $compare(m_areaOpacityRelated2);
        $compare(m_areaOpacityRelated3);
        $compare(m_unk52C);
        $compare(m_unk530);
        $compare(m_isUIObject);
        $compare(m_unk532);
        $compare(m_poweredOn);
        $compare(m_state);
        // $compare(m_animationRandomizedStartValue);
        // $compare(m_animationStart);
        $compare(m_unk540);
        $compare(m_unk544);
        $compare(m_unk548);
        $compare(m_randomFrameTime);
        $compare(m_visible);
        $compare(m_shouldNotHideAnimFreeze);
        // $compare(m_usesSpecialAnimation);
        $compare(m_frameTime);
        $compare(m_frames);
        // $compare(m_hasCustomAnimation);
        $compare(m_hasCustomRotation);
        $compare(m_disableRotation);
        $compare(m_rotationSpeed);
        $compare(m_rotationAngle);
        $compare(m_rotationDelta);
        $compare(m_rotationAnimationSpeed);
        $compare(m_animationRandomizedStart);
        $compare(m_animationSpeed);
        $compare(m_animationShouldUseSpeed);
        $compare(m_animateOnTrigger);
        $compare(m_disableDelayedLoop);
        $compare(m_disableAnimShine);
        $compare(m_singleFrame);
        $compare(m_animationOffset);
        $compare(m_animationTriggered);
        $compare(m_unkAnimationInt);
        $compare(m_maybeAnimationVariableXInt);
        $compare(m_maybeAnimationVariableYInt);
        $compare(m_animateOnlyWhenActive);
        $compare(m_isNoMultiActivate);
        $compare(m_isMultiActivate);
        $compare(m_activated);
        $compare(m_activatedByPlayer1);
        $compare(m_activatedByPlayer2);
        $compare(m_hasUniqueCoin);
        $compare(m_unknownBool);
        $compare(m_duration);
        $compare(m_opacity);
        $compare(m_triggerEffectPlaying);
        $compare(m_targetGroupID);
        $compare(m_centerGroupID);
        $compare(m_isTouchTriggered);
        $compare(m_isSpawnTriggered);
        $compare(m_hasCenterEffect);
        $compare(m_shakeStrength);
        $compare(m_shakeInterval);
        $compare(m_tintGround);
        $compare(m_usesPlayerColor1);
        $compare(m_usesPlayerColor2);
        $compare(m_usesBlending);
        $compare(m_moveOffset);
        $compare2(m_easingType);
        $compare(m_easingRate);
        $compare(m_lockToPlayerX);
        $compare(m_lockToPlayerY);
        $compare(m_lockToCameraX);
        $compare(m_lockToCameraY);
        $compare(m_useMoveTarget);
        $compare2(m_moveTargetMode);
        $compare(m_moveModX);
        $compare(m_moveModY);
        $compare(m_smallStep);
        $compare(m_isDirectionFollowSnap360);
        $compare(m_targetModCenterID);
        $compare(m_directionModeDistance);
        $compare(m_isDynamicMode);
        $compare(m_isSilent);
        $compare(m_specialTarget);
        $compare(m_rotationDegrees);
        $compare(m_times360);
        $compare(m_lockObjectRotation);
        $compare(m_rotationTargetID);
        $compare(m_rotationOffset);
        $compare(m_dynamicModeEasing);
        $compare(m_followXMod);
        $compare(m_followYMod);
        $compare(m_followYSpeed);
        $compare(m_followYDelay);
        $compare(m_followYOffset);
        $compare(m_followYMaxSpeed);
        $compare(m_fadeInDuration);
        $compare(m_holdDuration);
        $compare(m_fadeOutDuration);
        $compare(m_pulseMode);
        $compare(m_pulseTargetType);
        $compare(m_copyColorID);
        $compare(m_copyOpacity);
        $compare(m_pulseMainOnly);
        $compare(m_pulseDetailOnly);
        $compare(m_pulseExclusive);
        $compare(m_legacyHSV);
        $compare(m_activateGroup);
        $compare(m_touchHoldMode);
        $compare2(m_touchToggleMode);
        $compare2(m_touchPlayerMode);
        $compare(m_isDualMode);
        $compare(m_animationID);
        $compare(m_spawnXPosition);
        $compare(m_spawnOrder);
        // $compare(m_isMultiTriggered);
        $compare(m_previewDisable);
        $compare(m_spawnOrdered);
        $compare(m_triggerOnExit);
        $compare(m_itemID2);
        $compare(m_controlID);
        $compare(m_targetControlID);
        $compare(m_isDynamicBlock);
        $compare(m_itemID);
        $compare(m_targetPlayer1);
        $compare(m_targetPlayer2);
        $compare(m_followCPP);
        $compare(m_subtractCount);
        $compare(m_collectibleIsPickupItem);
        $compare(m_collectibleIsToggleTrigger);
        $compare(m_collectibleParticleID);
        $compare(m_collectiblePoints);
        // $compare(m_hasNoAnimation);
        $compare(m_unk698);
        $compare(m_forceModID);
        $compare(m_rotateFollowP1);
        $compare(m_rotateFollowP2);
        $compare(m_unk6a8);
        $compare(m_unk6ac);
        $compare(m_unk6b0);
        $compare(m_unk6b4);
        $compare(m_gravityValue);
        $compare(m_isSinglePTouch);
        $compare(m_zoomValue);
        $compare(m_cameraIsFreeMode);
        $compare(m_cameraEditCameraSettings);
        $compare(m_cameraEasingValue);
        $compare(m_cameraPaddingValue);
        $compare(m_cameraDisableGridSnap);
        $compare(m_endReversed);
        $compare(m_timeWarpTimeMod);
        $compare(m_shouldPreview);
        $compare(m_ordValue);
        $compare(m_channelValue);
        $compare(m_isReverse);
        $compare(m_speedModType);
        $compare(m_speedStart);
        $compare(m_secretCoinID);
        $compare(m_unk6f4);
        $compare(m_unk6f5);
        $compare(m_endPosition);
        $compare(m_spawnTriggerDelay);
        $compare(m_gravityMod);
        $compare(m_unk708);
        // $compare(m_objectLabel);
        $compare(m_ignoreGroupParent);
        $compare(m_ignoreLinkedObjects);
        $compare(m_channelChanged);

        return EditorUI::copyObjects(objects, copyColors, sort);
    } // copyObjects
};